#! /bin/sh

#export XDG_CURRENT_DESKTOP="bspwm"
#export DESKTOP_SESSION="bspwm"
#export XDG_SESSION_DESKTOP="bspwm"

#export XDG_DATA_DIRS="/run/current-system/sw/share:/usr/share"

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep "DP-4 connected") ]];
then
       xrandr --output DVI-D-0 --off \
       --output HDMI-0 --mode 1920x1080 --pos 0x840 --rotate left \
       --output DP-0 --mode 1920x1080 --pos 1400x0 --rotate normal \
       --output DP-1 --off \
       --output DP-2 --mode 1920x1080 --pos 3640x1260 --rotate normal \
       --output DP-3 --off \
       --output DP-4 --primary --mode 2560x1440 --rate 143.96 --pos 1080x1080 --rotate normal \
       --output DP-5 --off
       bspc monitor DP-4 -d I III IV IX
       bspc monitor HDMI-0 -d II
       bspc monitor DP-2 -d VII
       bspc monitor DP-0 -d V
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         5
bspc config window_gap          10

bspc config normal_border_color "#313244"
bspc config active_border_color "#313244"
bspc config focused_border_color "#cba6f7"
bspc config presel_feedback_color "#fab387"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 7ms

bspc rule -a Gimp desktop='VII' state=floating follow=on
bspc rule -a firefox desktop='II' follow=on
bspc rule -a kitty desktop='I' follow=on
bspc rule -a Code desktop='IV' follow=on
bspc rule -a Thunar desktop='III' follow=on
bspc rule -a mpv desktop='V' follow=on
bspc rule -a Spotify desktop='V' follow=on
bspc rule -a ayugram-desktop desktop='VII' follow=on
bspc rule -a telegram-desktop desktop='VII' follow=on
bspc rule -a Signal desktop='VII' follow=on
bspc rule -a Discord desktop='VII' follow=on
bspc rule -a Lutris desktop='IX' follow=on
bspc rule -a Steam desktop='IX' follow=on

feh --no-fehbg --bg-fill ~/.config/bspwm/wallpaper.jpg
#polybar bottom -c ~/.config/polybar/config.ini &
/run/current-system/sw/bin/lxqt-policykit-agent &
#systemctl --user restart polybar
thunar --daemon &
wmname LG3D &
xsetroot -cursor_name left_ptr &
#/usr/bin/dunst &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
#easyeffects --gapplication-service &
nvidia-settings --load-config-only &
#thunar --daemon &
#udiskie &
xinput --set-prop "12" "libinput Accel Profile Enabled" 0 1 0 &
#xsettingsd &
#~/.tumblerd.sh &
