#!/usr/bin/env bash
#
# Fresh install from the NixOS live ISO (root, with networking and flakes enabled).
#
# Quick clone + install:
#   curl -fsSL 'https://raw.githubusercontent.com/OWNER/REPO/BRANCH/install/curl-installer.sh' | sudo bash
#
# Already cloned:
#   cd /path/to/nix-config && sudo ./install/bootstrap.sh
#
# Non-interactive:
#   export INSTALL_NON_INTERACTIVE=1 INSTALL_I_UNDERSTAND_THIS_ERASES_THE_DISK=1
#   export PRESET=personal FLAKE_HOST=mybox DISK=/dev/disk/by-id/...
#   export DISKO_SCHEME=btrfs-luks-efi-simple
#   export LUKS_PASSWORD='...'   # LUKS + non-interactive only (avoid on shared / logged shells)
#
# Custom host fragment (relative to repo unless absolute):
#   export HOST_MODULE=hosts/templates/fragment.nix
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
export REPO_ROOT

# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/detect.sh"

LUKS_PASS_FILE=/tmp/disko-luks-password
cleanup_luks_file() {
  [[ -f "$LUKS_PASS_FILE" ]] && shred -u "$LUKS_PASS_FILE" 2>/dev/null || rm -f "$LUKS_PASS_FILE"
}

nix_system_for_uname() {
  case "$(uname -m)" in
    x86_64) echo "x86_64-linux" ;;
    aarch64) echo "aarch64-linux" ;;
    *) echo "x86_64-linux" ;;
  esac
}

resolve_path() {
  local p="$1"
  if [[ -z "$p" ]]; then
    echo ""
    return
  fi
  if [[ "$p" == /* ]]; then
    echo "$p"
  else
    echo "$REPO_ROOT/$p"
  fi
}

write_registry_local() {
  local flake_host="$1" user="$2" platform="$3" gpu="$4" system="$5"
  cat >"$REPO_ROOT/hosts/registry.local.nix" <<EOF
# Generated by install/bootstrap.sh — commit or merge into hosts/registry.nix when stable.
{
  ${flake_host} = {
    system = "${system}";
    username = "${user}";
    platform = "${platform}";
    gpu = "${gpu}";
    host = ./${flake_host};
  };
}
EOF
}

# Installer-managed host: disko module + rendered scheme + shared stack (+ optional fragment).
write_installer_stack_default() {
  local hdir="$1"
  cat >"$hdir/default.nix" <<'EOF'
{ inputs, lib, ... }:
{
  imports =
    [
      inputs.disko.nixosModules.disko
      ../../nixos/modules/system
      ../../nixos/modules/niri.nix
      ./hardware-configuration.nix
      ./disko-scheme.nix
    ]
    ++ lib.optional (builtins.pathExists ./host-fragment.nix) ./host-fragment.nix;
}
EOF
}

# Returns via global _HOST_PREP_MODE: stacked | template
prepare_host_tree() {
  local hostdir="$1" module_raw="$2"
  mkdir -p "$hostdir"
  _HOST_PREP_MODE=stacked

  if [[ -z "$module_raw" ]]; then
    rm -f "$hostdir/host-fragment.nix"
    return
  fi

  local mod
  mod="$(resolve_path "$module_raw")"
  [[ -e "$mod" ]] || die "HOST_MODULE not found: $mod"

  if [[ -d "$mod" ]]; then
    cp -a "$mod/." "$hostdir/"
    [[ -f "$hostdir/default.nix" ]] || die "HOST_MODULE directory must contain default.nix ($mod)"
    _HOST_PREP_MODE=template
    return
  fi

  if [[ -f "$mod" ]]; then
    cp -f "$mod" "$hostdir/host-fragment.nix"
    return
  fi

  die "HOST_MODULE must be a file or directory: $mod"
}

maybe_warn_template_disko() {
  local hostdir="$1"
  if grep -qE 'disko-scheme|nixosModules\.disko' "$hostdir/default.nix" 2>/dev/null; then
    return
  fi
  echo "warning: template host under $hostdir does not reference disko + ./disko-scheme.nix."
  echo "         See hosts/_templates/installer-default.nix (./disko-scheme.nix is written beside default.nix)."
}

prepare_luks_passphrase() {
  local scheme="$1"
  [[ "$scheme" == *luks* ]] || return 0

  trap cleanup_luks_file EXIT

  if [[ "${INSTALL_NON_INTERACTIVE:-}" == "1" ]]; then
    [[ -n "${LUKS_PASSWORD:-}" ]] || die "set LUKS_PASSWORD for non-interactive LUKS install"
    printf '%s' "$LUKS_PASSWORD" >"$LUKS_PASS_FILE"
    chmod 400 "$LUKS_PASS_FILE"
    return
  fi

  local a b
  read -r -s -p "LUKS passphrase: " a
  echo
  read -r -s -p "LUKS passphrase (again): " b
  echo
  [[ "$a" == "$b" ]] || die "passphrases do not match"
  [[ -n "$a" ]] || die "empty passphrase"
  printf '%s' "$a" >"$LUKS_PASS_FILE"
  chmod 400 "$LUKS_PASS_FILE"
}

run_disko_locked() {
  local config_path="$1"
  command -v nix &>/dev/null || die "nix is not available in PATH"
  nix run ".#disko" -- --mode disko "$config_path"
}

main() {
  require_root
  require_repo

  cd "$REPO_ROOT" || die "cannot cd to $REPO_ROOT"
  rm -f "$LUKS_PASS_FILE"

  if [[ ! -f flake.lock ]]; then
    echo "flake.lock missing — running nix flake lock"
    nix flake lock
  fi

  local platform gpu system
  platform="$(detect_platform_tag)"
  gpu="$(detect_gpu_tag)"
  system="$(nix_system_for_uname)"

  local scheme disk flake_host username host_module

  host_module="${HOST_MODULE:-}"

  if [[ "${PRESET:-}" == "personal" ]]; then
    flake_host="${FLAKE_HOST:-nixos-install}"
    username="${NEW_USERNAME:-integrus}"
    scheme="${DISKO_SCHEME:-btrfs-efi-simple}"
    disk="${DISK:-}"
    echo "PRESET=personal: flakeHost=$flake_host user=$username scheme=$scheme system=$system"
    if [[ "${INSTALL_NON_INTERACTIVE:-}" != "1" ]]; then
      read -r -p "Platform [$platform] (enter to keep): " p_o
      [[ -n "${p_o:-}" ]] && platform="$p_o"
      read -r -p "GPU tag [$gpu] (enter to keep): " g_o
      [[ -n "${g_o:-}" ]] && gpu="$g_o"
    fi
  else
    echo "Detected platform tag: $platform  gpu tag: $gpu  (system: $system)"
    if [[ "${INSTALL_NON_INTERACTIVE:-}" == "1" ]]; then
      flake_host="${FLAKE_HOST:-nixos-install}"
      username="${NEW_USERNAME:-integrus}"
      scheme="${DISKO_SCHEME:-btrfs-efi-simple}"
    else
      read -r -p "Flake host name / hosts/ subdirectory [nixos-install]: " flake_host
      flake_host="${flake_host:-nixos-install}"
      read -r -p "Primary username [integrus]: " username
      username="${username:-integrus}"
      echo "Disko schemes: btrfs-efi-simple, btrfs-luks-efi-simple, ext4-efi-simple"
      read -r -p "Disko scheme [btrfs-efi-simple]: " scheme
      scheme="${scheme:-btrfs-efi-simple}"
      read -r -p "Platform tag override (empty = keep '$platform'): " p_o
      [[ -n "${p_o:-}" ]] && platform="$p_o"
      read -r -p "GPU tag override (empty = keep '$gpu'): " g_o
      [[ -n "${g_o:-}" ]] && gpu="$g_o"
      if [[ -z "$host_module" ]]; then
        read -r -p "HOST_MODULE: path to extra .nix or host dir (empty = repo defaults): " hmin
        host_module="${hmin:-}"
      fi
    fi
  fi

  if [[ -z "${disk:-}" ]]; then
    [[ "${INSTALL_NON_INTERACTIVE:-}" == "1" ]] && die "set DISK for non-interactive install"
    echo "Block devices:"
    lsblk -o NAME,SIZE,TYPE,FSTYPE,MOUNTPOINTS 2>/dev/null || lsblk || true
    read -r -p "Target device (/dev/disk/by-id/... recommended): " disk
  fi
  [[ -n "${disk:-}" ]] || die "set DISK or enter a device path"

  confirm_wipe "$disk"

  local hostdir="$REPO_ROOT/hosts/$flake_host"
  _HOST_PREP_MODE=stacked
  prepare_host_tree "$hostdir" "$host_module"

  local scheme_file="$REPO_ROOT/disko/schemes/${scheme}.nix"
  [[ -f "$scheme_file" ]] || die "unknown scheme '$scheme' (missing $scheme_file)"

  prepare_luks_passphrase "$scheme"

  write_registry_local "$flake_host" "$username" "$platform" "$gpu" "$system"

  local renderer="$SCRIPT_DIR/lib/render_disko.py"
  [[ -f "$renderer" ]] || die "missing $renderer"
  command -v python3 &>/dev/null || die "python3 is required to inject the disk path safely"

  local rendered="$hostdir/disko-scheme.nix"
  python3 "$renderer" "$scheme_file" "$disk" "$rendered"

  if [[ "${_HOST_PREP_MODE:-}" == "template" ]]; then
    maybe_warn_template_disko "$hostdir"
  else
    write_installer_stack_default "$hostdir"
  fi

  echo "Running disko (flake app #disko, pinned by flake.lock) …"
  run_disko_locked "$rendered"

  echo "Generating hardware-configuration.nix from /mnt …"
  local tmp
  tmp="$(mktemp -d)"
  nixos-generate-config --dir "$tmp" --root /mnt
  cp "$tmp/hardware-configuration.nix" "$hostdir/"
  rm -rf "$tmp"

  echo "nixos-install --flake $REPO_ROOT#$flake_host"
  nixos-install --no-root-password --flake "$REPO_ROOT#$flake_host"

  cleanup_luks_file
  trap - EXIT

  echo "Finished. Set passwords (passwd), verify boot entries, then reboot."
}

main "$@"
