#!/usr/bin/env bash
#
# Fresh install from the NixOS live ISO (root, with networking and flakes enabled).
#
# Quick clone + install:
#   curl -fsSL 'https://raw.githubusercontent.com/OWNER/REPO/BRANCH/install/curl-installer.sh' | sudo bash
#
# This repo’s default Git URL enables a one-screen summary: you confirm with Enter, then
# disk wipe + LUKS (if applicable). Disable: OWNER_QUICKSTART=0
#
# Already cloned:
#   cd /path/to/nix-config && sudo ./install/bootstrap.sh
#
# Non-interactive:
#   export INSTALL_NON_INTERACTIVE=1 INSTALL_I_UNDERSTAND_THIS_ERASES_THE_DISK=1
#   export PRESET=personal FLAKE_HOST=mybox DISK=/dev/disk/by-id/...
#   export DISKO_SCHEME=btrfs-luks-efi-simple
#   export LUKS_PASSWORD='...'
#
# Custom host fragment:
#   export HOST_MODULE=hosts/templates/fragment.nix
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
export REPO_ROOT

# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/common.sh"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/detect.sh"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/quickstart.sh"

# shellcheck disable=SC2034
host_module=""
flake_host=""
username=""
scheme=""
disk=""
platform=""
gpu=""
system=""

LUKS_PASS_FILE=/tmp/disko-luks-password
cleanup_luks_file() {
  if [[ -f "$LUKS_PASS_FILE" ]]; then
    if command -v shred &>/dev/null; then
      shred -u "$LUKS_PASS_FILE" 2>/dev/null || rm -f "$LUKS_PASS_FILE"
    else
      rm -f "$LUKS_PASS_FILE"
    fi
  fi
}

nix_system_for_uname() {
  case "$(uname -m)" in
    x86_64) echo "x86_64-linux" ;;
    aarch64) echo "aarch64-linux" ;;
    *) echo "x86_64-linux" ;;
  esac
}

resolve_path() {
  local p="$1"
  if [[ -z "$p" ]]; then
    echo ""
    return
  fi
  if [[ "$p" == /* ]]; then
    echo "$p"
  else
    echo "$REPO_ROOT/$p"
  fi
}

write_registry_local() {
  local flake_h="$1" user="$2" plat="$3" g="$4" sys="$5"
  cat >"$REPO_ROOT/hosts/registry.local.nix" <<EOF
# Generated by install/bootstrap.sh — commit or merge into hosts/registry.nix when stable.
{
  ${flake_h} = {
    system = "${sys}";
    username = "${user}";
    platform = "${plat}";
    gpu = "${g}";
    host = ./${flake_h};
  };
}
EOF
}

write_installer_stack_default() {
  local hdir="$1"
  cat >"$hdir/default.nix" <<'EOF'
{ inputs, lib, ... }:
{
  imports =
    [
      inputs.disko.nixosModules.disko
      ../../nixos/modules/system
      ../../nixos/modules/niri.nix
      ./hardware-configuration.nix
      ./disko-scheme.nix
    ]
    ++ lib.optional (builtins.pathExists ./host-fragment.nix) ./host-fragment.nix;
}
EOF
}

prepare_host_tree() {
  local hostdir="$1" module_raw="$2"
  mkdir -p "$hostdir"
  _HOST_PREP_MODE=stacked

  if [[ -z "$module_raw" ]]; then
    rm -f "$hostdir/host-fragment.nix"
    return
  fi

  local mod
  mod="$(resolve_path "$module_raw")"
  [[ -e "$mod" ]] || die "HOST_MODULE not found: $mod"

  if [[ -d "$mod" ]]; then
    cp -a "$mod/." "$hostdir/"
    [[ -f "$hostdir/default.nix" ]] || die "HOST_MODULE directory must contain default.nix ($mod)"
    _HOST_PREP_MODE=template
    return
  fi

  if [[ -f "$mod" ]]; then
    cp -f "$mod" "$hostdir/host-fragment.nix"
    return
  fi

  die "HOST_MODULE must be a file or directory: $mod"
}

maybe_warn_template_disko() {
  local hostdir="$1"
  if grep -qE 'disko-scheme|nixosModules\.disko' "$hostdir/default.nix" 2>/dev/null; then
    return
  fi
  echo "warning: template host under $hostdir does not reference disko + ./disko-scheme.nix."
  echo "         See hosts/_templates/installer-default.nix (./disko-scheme.nix is written beside default.nix)."
}

prepare_luks_passphrase() {
  local sch="$1"
  [[ "$sch" == *luks* ]] || return 0

  trap cleanup_luks_file EXIT

  if [[ "${INSTALL_NON_INTERACTIVE:-}" == "1" ]]; then
    [[ -n "${LUKS_PASSWORD:-}" ]] || die "set LUKS_PASSWORD for non-interactive LUKS install"
    printf '%s' "$LUKS_PASSWORD" >"$LUKS_PASS_FILE"
    chmod 400 "$LUKS_PASS_FILE"
    return
  fi

  local a b
  read -r -s -p "LUKS passphrase: " a
  echo
  read -r -s -p "LUKS passphrase (again): " b
  echo
  [[ "$a" == "$b" ]] || die "passphrases do not match"
  [[ -n "$a" ]] || die "empty passphrase"
  printf '%s' "$a" >"$LUKS_PASS_FILE"
  chmod 400 "$LUKS_PASS_FILE"
}

run_disko_locked() {
  local config_path="$1"
  command -v nix &>/dev/null || die "nix is not available in PATH"
  nix run ".#disko" -- --mode disko "$config_path"
}

run_full_interactive_wizard() {
  echo "Detected platform tag: $platform  gpu tag: $gpu  (system: $system)"
  if [[ "${INSTALL_NON_INTERACTIVE:-}" == "1" ]]; then
    flake_host="${FLAKE_HOST:-nixos-install}"
    username="${NEW_USERNAME:-integrus}"
    scheme="${DISKO_SCHEME:-btrfs-efi-simple}"
    return
  fi

  read -r -p "Flake host name / hosts/ subdirectory [nixos-install]: " _fh
  flake_host="${_fh:-nixos-install}"
  read -r -p "Primary username [integrus]: " _un
  username="${_un:-integrus}"
  echo "Disko schemes: btrfs-efi-simple, btrfs-luks-efi-simple, ext4-efi-simple"
  read -r -p "Disko scheme [btrfs-efi-simple]: " _sc
  scheme="${_sc:-btrfs-efi-simple}"
  read -r -p "Platform tag override (empty = keep '$platform'): " p_o
  [[ -n "${p_o:-}" ]] && platform="$p_o"
  read -r -p "GPU tag override (empty = keep '$gpu'): " g_o
  [[ -n "${g_o:-}" ]] && gpu="$g_o"
  if [[ -z "$host_module" ]]; then
    read -r -p "HOST_MODULE: path to extra .nix or host dir (empty = repo defaults): " hmin
    host_module="${hmin:-}"
  fi
}

main() {
  require_root
  require_repo

  cd "$REPO_ROOT" || die "cannot cd to $REPO_ROOT"
  rm -f "$LUKS_PASS_FILE"

  if [[ ! -f flake.lock ]]; then
    echo "flake.lock missing — running nix flake lock"
    nix flake lock
  fi

  platform="$(detect_platform_tag)"
  gpu="$(detect_gpu_tag)"
  system="$(nix_system_for_uname)"
  local machine suggested_disk
  machine="$(detect_machine_label)"
  suggested_disk="$(suggest_install_disk || true)"

  host_module="${HOST_MODULE:-}"

  if [[ "${PRESET:-}" == "personal" ]]; then
    flake_host="${FLAKE_HOST:-nixos-install}"
    username="${NEW_USERNAME:-integrus}"
    scheme="${DISKO_SCHEME:-btrfs-efi-simple}"
    disk="${DISK:-}"
    echo "PRESET=personal: flakeHost=$flake_host user=$username scheme=$scheme system=$system"
    if [[ "${INSTALL_NON_INTERACTIVE:-}" != "1" ]]; then
      read -r -p "Platform [$platform] (enter to keep): " p_o
      [[ -n "${p_o:-}" ]] && platform="$p_o"
      read -r -p "GPU tag [$gpu] (enter to keep): " g_o
      [[ -n "${g_o:-}" ]] && gpu="$g_o"
    fi
  elif owner_quickstart_wanted; then
    username="$(owner_default_username)"
    scheme="$(owner_default_scheme_for_platform "$platform")"
    flake_host="$(owner_suggest_flake_host)"
    disk="${DISK:-$suggested_disk}"
    print_install_summary "$machine" "$platform" "$gpu" "$system" "$disk" "$scheme" "$flake_host" "$username"
    local qc
    prompt_quick_correct
    qc=$?
    if [[ "$qc" -eq 2 ]]; then
      echo "Switching to step-by-step prompts…"
      run_full_interactive_wizard
    elif [[ "$qc" -eq 0 ]]; then
      echo "Using quick defaults (OWNER_QUICKSTART=0 next time for the full wizard)."
    else
      run_full_interactive_wizard
    fi
  else
    run_full_interactive_wizard
  fi

  if [[ -z "${disk:-}" ]]; then
    [[ "${INSTALL_NON_INTERACTIVE:-}" == "1" ]] && die "set DISK for non-interactive install"
    echo "Block devices:"
    lsblk -o NAME,SIZE,TYPE,FSTYPE,MOUNTPOINTS 2>/dev/null || lsblk || true
    local defdisk="${suggested_disk:-}"
    read -r -p "Target device [${defdisk:-type path}]: " _dk
    disk="${_dk:-$defdisk}"
  fi
  [[ -n "${disk:-}" ]] || die "set DISK or enter a device path"

  confirm_wipe "$disk"

  local hostdir="$REPO_ROOT/hosts/$flake_host"
  _HOST_PREP_MODE=stacked
  prepare_host_tree "$hostdir" "$host_module"

  local scheme_file="$REPO_ROOT/disko/schemes/${scheme}.nix"
  [[ -f "$scheme_file" ]] || die "unknown scheme '$scheme' (missing $scheme_file)"

  prepare_luks_passphrase "$scheme"

  write_registry_local "$flake_host" "$username" "$platform" "$gpu" "$system"

  local renderer="$SCRIPT_DIR/lib/render_disko.py"
  [[ -f "$renderer" ]] || die "missing $renderer"
  command -v python3 &>/dev/null || die "python3 is required to inject the disk path safely"

  local rendered="$hostdir/disko-scheme.nix"
  python3 "$renderer" "$scheme_file" "$disk" "$rendered"

  if [[ "${_HOST_PREP_MODE:-}" == "template" ]]; then
    maybe_warn_template_disko "$hostdir"
  else
    write_installer_stack_default "$hostdir"
  fi

  echo "Running disko (flake app #disko, pinned by flake.lock) …"
  run_disko_locked "$rendered"

  echo "Regenerating hardware-configuration.nix from /mnt (you should not have to copy anything by hand) …"
  local tmp
  tmp="$(mktemp -d)"
  nixos-generate-config --dir "$tmp" --root /mnt
  cp "$tmp/hardware-configuration.nix" "$hostdir/"
  rm -rf "$tmp"

  echo "nixos-install --flake $REPO_ROOT#$flake_host"
  nixos-install --no-root-password --flake "$REPO_ROOT#$flake_host"

  cleanup_luks_file
  trap - EXIT

  echo "Done. passwd, reboot, coffee."
}

main "$@"
