#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10

bspc config normal_border_color "#83a598"
bspc config active_border_color "#83a598"
bspc config focused_border_color "#d3869b"
bspc config presel_feedback_color "#fe8019"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 7ms

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#udiskie &
thunar --daemon &
#~/.tumblerd.sh &
wmname LG3D &
#nvidia-settings --load-config-only &
xsetroot -cursor_name left_ptr &
feh --no-fehbg --bg-fill ~/.config/bspwm/wallpaper.png
#easyeffects --gapplication-service &
#/usr/bin/dunst &
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
#xinput --set-prop "12" "libinput Accel Profile Enabled" 0 1 0 &
#xsettingsd &