#! /bin/sh

export XDG_CURRENT_DESKTOP="bspwm"
export DESKTOP_SESSION="bspwm"
export XDG_SESSION_DESKTOP="bspwm"

export XDG_DATA_DIRS="/run/current-system/sw/share:/usr/share"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          10

bspc config normal_border_color "#89b4fa"
bspc config active_border_color "#89b4fa"
bspc config focused_border_color "#f5c2e7"
bspc config presel_feedback_color "#fab387"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 7ms

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a kitty desktop='^1' follow=on
bspc rule -a Code desktop='^4' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a mpv desktop='^5' follow=on
bspc rule -a Spotify desktop='^6' follow=on
bspc rule -a ayugram-desktop desktop='^7' follow=on
bspc rule -a telegram-desktop desktop='^7' follow=on
bspc rule -a Discord desktop='^8' follow=on
bspc rule -a Lutris desktop='^9' follow=on
bspc rule -a Steam desktop='^9' follow=on

feh --no-fehbg --bg-fill ~/.config/bspwm/wallpaper.jpg
/run/current-system/sw/bin/lxqt-policykit-agent &
systemctl --user restart polybar
thunar --daemon &
wmname LG3D &
xsetroot -cursor_name left_ptr &
#/usr/bin/dunst &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
#easyeffects --gapplication-service &
#nvidia-settings --load-config-only &
#thunar --daemon &
#udiskie &
#xinput --set-prop "12" "libinput Accel Profile Enabled" 0 1 0 &
#xsettingsd &
#~/.tumblerd.sh &